{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"Logo.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"EmojiKit helps you manage emojis in Swift-based software on all major Apple platforms (iOS, macOS, tvOS and watchOS)."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"EmojiKit provides you with all you need to work with emojis, including unicode information, localization support, categories, skin tones, version information, etc. It also includes UI components like emoji grids and pickers."}]},{"anchor":"Getting-started","level":2,"type":"heading","text":"Getting started"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Getting-Started"},{"type":"text","text":" article helps you get started with EmojiKit. After that, check out the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Features"},{"type":"text","text":" article for more information about the features the library provides, and the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Views"},{"type":"text","text":" article for more information about built-in views."}]},{"anchor":"License","level":2,"type":"heading","text":"License"},{"type":"paragraph","inlineContent":[{"type":"text","text":"EmojiKit requires a commercial license to be used. You can sign up for a free trial on the "},{"type":"reference","isActive":true,"identifier":"https:\/\/kankoda.com\/emojikit"},{"type":"text","text":" and use the license key that you receive to start using the library."}]},{"anchor":"Repository","level":2,"type":"heading","text":"Repository"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information, demo apps, issue tracking, etc., visit the "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/Kankoda\/EmojiKit"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/emojikit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/emojikit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"EmojiKit is helps you manage emojis in your Swift-based software."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"EmojiKit","title":"EmojiKit","symbolKind":"module","role":"collection","modules":[{"name":"EmojiKit"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Getting-Started","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Features","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Views"]},{"title":"Essentials","identifiers":["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Emoji"]},{"title":"Frequent","identifiers":["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/FrequentEmojiProvider"]},{"title":"Licenses","identifiers":["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/License","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/LicenseEngine","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/LicenseError","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/LicenseFeature","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/LicenseIntegrations","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/LicenseServiceType"]}],"references":{"doc://com.kankoda.EmojiKit/documentation/EmojiKit/LicenseEngine":{"role":"symbol","title":"LicenseEngine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseEngine"}],"abstract":[{"type":"text","text":"This is the most central class in LicenseKit and is used to"},{"type":"text","text":" "},{"type":"text","text":"resolve license keys."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/LicenseEngine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseEngine"}],"url":"\/documentation\/emojikit\/licenseengine"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/LicenseError":{"role":"symbol","title":"LicenseError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseError"}],"abstract":[{"type":"text","text":"This enum defines various license errors that can be thrown"},{"type":"text","text":" "},{"type":"text","text":"when registering a license key or trying to access features"},{"type":"text","text":" "},{"type":"text","text":"that require a specific license type."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/LicenseError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseError"}],"url":"\/documentation\/emojikit\/licenseerror"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/Features":{"role":"article","title":"Features","abstract":[{"type":"text","text":"This article describes the features that EmojiKit provides."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Features","kind":"article","type":"topic","url":"\/documentation\/emojikit\/features"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/LicenseIntegrations":{"role":"symbol","title":"LicenseIntegrations","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseIntegrations"}],"abstract":[{"type":"text","text":"This namespace is used to contain integration-related types."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/LicenseIntegrations","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseIntegrations"}],"url":"\/documentation\/emojikit\/licenseintegrations"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit":{"role":"collection","title":"EmojiKit","abstract":[{"type":"text","text":"EmojiKit is helps you manage emojis in your Swift-based software."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit","kind":"symbol","type":"topic","url":"\/documentation\/emojikit"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/LicenseFeature":{"role":"symbol","title":"LicenseFeature","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseFeature"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any type that should be"},{"type":"text","text":" "},{"type":"text","text":"used as a license-based feature."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/LicenseFeature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseFeature"}],"url":"\/documentation\/emojikit\/licensefeature"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/Emoji":{"role":"symbol","title":"Emoji","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Emoji"}],"abstract":[{"type":"text","text":"This type represents an emoji and serves as a namespace for"},{"type":"text","text":" "},{"type":"text","text":"emoji-related types and functionality."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Emoji","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Emoji"}],"url":"\/documentation\/emojikit\/emoji"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/EmojiKitVersionNumber":{"role":"symbol","title":"EmojiKitVersionNumber","fragments":[{"kind":"identifier","text":"EmojiKitVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for EmojiKit."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/EmojiKitVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/emojikit\/emojikitversionnumber"},"Logo.png":{"alt":"EmojiKit logo","type":"image","identifier":"Logo.png","variants":[{"url":"\/images\/Logo.png","traits":["1x","light"]}]},"https://github.com/Kankoda/EmojiKit":{"title":"project repository","titleInlineContent":[{"type":"text","text":"project repository"}],"type":"link","identifier":"https:\/\/github.com\/Kankoda\/EmojiKit","url":"https:\/\/github.com\/Kankoda\/EmojiKit"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/License":{"role":"symbol","title":"License","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"License"}],"abstract":[{"type":"text","text":"This struct represents a software license and also works as"},{"type":"text","text":" "},{"type":"text","text":"a namespace for license-related types."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/License","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"License"}],"url":"\/documentation\/emojikit\/license"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/FrequentEmojiProvider":{"role":"symbol","title":"FrequentEmojiProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FrequentEmojiProvider"}],"abstract":[{"type":"text","text":"This protocol can be implemented by types that can return a"},{"type":"text","text":" "},{"type":"text","text":"list of frequently used emojis."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/FrequentEmojiProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FrequentEmojiProvider"}],"url":"\/documentation\/emojikit\/frequentemojiprovider"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/EmojiKitVersionString":{"role":"symbol","title":"EmojiKitVersionString","fragments":[{"kind":"identifier","text":"EmojiKitVersionString"}],"abstract":[{"type":"text","text":"Project version string for EmojiKit."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/EmojiKitVersionString","kind":"symbol","type":"topic","url":"\/documentation\/emojikit\/emojikitversionstring"},"https://kankoda.com/emojikit":{"title":"EmojiKit website","titleInlineContent":[{"type":"text","text":"EmojiKit website"}],"type":"link","identifier":"https:\/\/kankoda.com\/emojikit","url":"https:\/\/kankoda.com\/emojikit"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/Getting-Started":{"role":"article","title":"Getting started","abstract":[{"type":"text","text":"This article describes how to get started with EmojiKit."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Getting-Started","kind":"article","type":"topic","url":"\/documentation\/emojikit\/getting-started"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/Views":{"role":"article","title":"Views","abstract":[{"type":"text","text":"This article describes the views that EmojiKit provides."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Views","kind":"article","type":"topic","url":"\/documentation\/emojikit\/views"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/LicenseServiceType":{"role":"symbol","title":"LicenseServiceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseServiceType"}],"abstract":[{"type":"text","text":"This enum defines various license service types that can be"},{"type":"text","text":" "},{"type":"text","text":"used to get customer licenses."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/LicenseServiceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseServiceType"}],"url":"\/documentation\/emojikit\/licenseservicetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Getting-Started","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Features","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Views"]},{"title":"Variables","identifiers":["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/EmojiKitVersionNumber","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/EmojiKitVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}