{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Before you can start using the library, you have to install it with the Swift Package Panager and link it to the main app target or library."}]},{"anchor":"Installation","level":2,"type":"heading","text":"Installation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"EmojiKit can be installed with the Swift Package Manager:"}]},{"type":"codeListing","syntax":null,"code":["https:\/\/github.com\/Kankoda\/EmojiKit.git"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"EmojiKit only has to be added to the main app target. If you are using EmojiKit with a library, make sure to set up your Swift package so that users get both your library and EmojiKit when fetching your package."}]},{"anchor":"License","level":2,"type":"heading","text":"License"},{"type":"paragraph","inlineContent":[{"type":"text","text":"EmojiKit requires a commercial license to be used. You can sign up for a free trial on the "},{"type":"reference","isActive":true,"identifier":"https:\/\/kankoda.com\/emojikit"},{"type":"text","text":" and use the license key that you receive to start using the library."}]},{"anchor":"How-to-setup-EmojiKit-in-an-app","level":2,"type":"heading","text":"How to setup EmojiKit in an app"},{"type":"paragraph","inlineContent":[{"type":"text","text":"EmojiKit requires a commercial license to be used."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"After purchasing a license from the "},{"overridingTitleInlineContent":[{"type":"text","text":"EmojiKit website"}],"isActive":true,"type":"reference","identifier":"https:\/\/kankoda.com\/emojikit","overridingTitle":"EmojiKit website"},{"type":"text","text":", you can register your license key like this:"}]},{"type":"codeListing","syntax":"swift","code":["import EmojiKit","","@main","struct MyApp: App {","","    var body: some Scene {","        WindowGroup {","            ContentView()","                .task(setupEmojiKit)","        }","    }","}","","extension MyApp {","","    func setupEmojiKit() async throws {","        do {","            try await License.register(licenseKey: \"your-license-key\")","            \/\/ Your app can now use EmojiKit features","        } catch {","            let error = error as? LicenseError","            \/\/ Handle this error somehow","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since the license registration is async, you may want to set some observable state once the registration succeeds, to ensure that the app updates properly. You may also want to handle any potential errors, in case the registration fails."}]},{"anchor":"How-to-setup-EmojiKit-in-a-library","level":2,"type":"heading","text":"How to setup EmojiKit in a library"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In a library or SDK, you should provide en entry-point for developers to set up your library, in which your library can register your license key to unlock EmojiKit-specific features."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, this example library provides a static setup function, that developers can call to set up the library:"}]},{"type":"codeListing","syntax":"swift","code":["import EmojiKit","","public struct ExampleLibrary {","","    public static func setup() throws {","        do {","            try await License.register(licenseKey: \"your-license-key\")","            \/\/ Your library or SDK can now use EmojiKit features","        } catch {","            let error = error as? LicenseError","            \/\/ Handle this error somehow","            throw error","        }","    } ","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Unlike apps, your library can use the async nature of the registration to communicate to developers when the registration finishes, after which your library can use EmojiKit-specific features."}]},{"anchor":"How-to-use-emojis","level":2,"type":"heading","text":"How to use emojis"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once you have registered a license key, you can start using the library. The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Getting-Started"},{"type":"text","text":" article helps you get started with EmojiKit. Check out the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Features"},{"type":"text","text":" article for more information about the features the library provides, and the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Views"},{"type":"text","text":" article for more information about built-in views."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/emojikit\/getting-started"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/emojikit\/getting-started"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Getting-Started","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article describes how to get started with EmojiKit."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Getting started","role":"article","modules":[{"name":"EmojiKit"}]},"hierarchy":{"paths":[["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Features","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Views"],"generated":true}],"references":{"doc://com.kankoda.EmojiKit/documentation/EmojiKit/Views":{"role":"article","title":"Views","abstract":[{"type":"text","text":"This article describes the views that EmojiKit provides."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Views","kind":"article","type":"topic","url":"\/documentation\/emojikit\/views"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/Getting-Started":{"role":"article","title":"Getting started","abstract":[{"type":"text","text":"This article describes how to get started with EmojiKit."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Getting-Started","kind":"article","type":"topic","url":"\/documentation\/emojikit\/getting-started"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/Features":{"role":"article","title":"Features","abstract":[{"type":"text","text":"This article describes the features that EmojiKit provides."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Features","kind":"article","type":"topic","url":"\/documentation\/emojikit\/features"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit":{"role":"collection","title":"EmojiKit","abstract":[{"type":"text","text":"EmojiKit is helps you manage emojis in your Swift-based software."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit","kind":"symbol","type":"topic","url":"\/documentation\/emojikit"},"https://kankoda.com/emojikit":{"title":"EmojiKit website","titleInlineContent":[{"type":"text","text":"EmojiKit website"}],"type":"link","identifier":"https:\/\/kankoda.com\/emojikit","url":"https:\/\/kankoda.com\/emojikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Features","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Views"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}