{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Getting-Started"},{"type":"text","text":" article has information on how to add EmojiKit to your project and register your license key. This is required before using many of the features that are listed below."}]},{"anchor":"Grid","level":2,"type":"heading","text":"Grid"},{"type":"paragraph","inlineContent":[{"type":"text","text":"EmojiKit has an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Emoji\/Grid"},{"type":"text","text":" that lets you list emojis in a horizontal or vertical grid."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The following code renders a standard vertical grid that uses a standard configuration and standard item views:"}]},{"type":"codeListing","syntax":"swift","code":["struct ContentView: View {","","    var body: some View {","        ScrollView(.vertical) {","            try? Emoji.Grid { ","                $0.view ","            }","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is the equivalent of typing out all the default parameter values:"}]},{"type":"codeListing","syntax":"swift","code":["struct ContentView: View {","","    var body: some View {","        ScrollView(.vertical) {","            try? Emoji.Grid(","                emojis: .all,","                axes: .vertical,","                config: .standard,","                emojiView: { $0.view }","            )","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"emoji-grid-vertical.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can provide a custom configuration to change item size, font size, spacing, etc., and customize the view for all or some emojis:"}]},{"type":"codeListing","syntax":"swift","code":["struct ContentView: View {","","    var body: some View {","        ScrollView(axis) {","            try? Emoji.Grid(","                emojis: .all,","                axes: axis,","                config: .init(","                    font: .largeTitle,","                    itemSize: 35,","                    itemSpacing: 10","                ),","                emojiView: { params in","                    let isCrazy = params.emoji.char == \"🤪\"","                    params.view","                        .rotationEffect(.degrees(isCrazy ? 180 : 0))","                        .scaleEffect(isCrazy ? 1.5 : 1)","                }","            )","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"emoji-grid-custom.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since the font size will not automatically define the item size, make sure that your custom configuration looks good on all device types."}]},{"anchor":"Picker","level":2,"type":"heading","text":"Picker"},{"type":"paragraph","inlineContent":[{"type":"text","text":"EmojiKit has an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Emoji\/Picker"},{"type":"text","text":" that lets you pick emojis from a horizontally or vertically scrolling grid."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The following code renders a standard, vertically scrolling picker that uses a standard configuration and standard item views:"}]},{"type":"codeListing","syntax":"swift","code":["struct ContentView: View {","","    @State","    private var selection: Emoji?","","    var body: some View {","        try? Emoji.Picker(","            selection: $selection","        ) {","            $0.view","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is the equivalent of typing out all the default parameter values:"}]},{"type":"codeListing","syntax":"swift","code":["struct ContentView: View {","","    @State","    private var selection: Emoji?","","    var body: some View {","        ScrollView(.vertical) {","            try? Emoji.Grid(","                selection: $selection,","                emojis: .all,","                axes: .vertical,","                config: .standard,","                action: { _ in },","                emojiView: { $0.view }","            )","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"emoji-picker-vertical.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since the picker currently doesn’t highlight the selected emoji, you can adjust the view builder to render the selected emoji differently:"}]},{"type":"codeListing","syntax":"swift","code":["try? Emoji.Picker(","    selection: $selection,","    emojis: .all,","    axes: .vertical,","    action: { print($0) },","    emojiView: { params in","        let isSelected = params.isSelected","        params.view","            .scaleEffect(isSelected ? 1 : 0.9)","            .background(Circle()","                .stroke(isSelected ? .blue : .clear, lineWidth: 1)","            )","    }",")"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The code above injects a custom action that prints the selected emoji (you can do this by observing the binding as well) and highlights the selected emoji by scaling it up and stroking it with a blue circle:"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"emoji-picker-custom.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The picker configuration lets you configure the grid and selection animation in full detail as well."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The picker will automatically add all available skintones as secondary callout items:"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"emoji-picker-callout.png"}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that these callouts only work on iOS 16.4 and macOS 12."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/emojikit\/views"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/emojikit\/views"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Views","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article describes the views that EmojiKit provides."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Views","role":"article","modules":[{"name":"EmojiKit"}]},"hierarchy":{"paths":[["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Getting-Started","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Features"],"generated":true}],"references":{"doc://com.kankoda.EmojiKit/documentation/EmojiKit/Features":{"role":"article","title":"Features","abstract":[{"type":"text","text":"This article describes the features that EmojiKit provides."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Features","kind":"article","type":"topic","url":"\/documentation\/emojikit\/features"},"emoji-picker-vertical.png":{"alt":"Emoji Picker","type":"image","identifier":"emoji-picker-vertical.png","variants":[{"url":"\/images\/emoji-picker-vertical.png","traits":["1x","light"]}]},"emoji-picker-custom.png":{"alt":"Emoji Picker with custom configuration","type":"image","identifier":"emoji-picker-custom.png","variants":[{"url":"\/images\/emoji-picker-custom.png","traits":["1x","light"]}]},"emoji-grid-custom.png":{"alt":"Emoji Grid with custom configuration","type":"image","identifier":"emoji-grid-custom.png","variants":[{"url":"\/images\/emoji-grid-custom.png","traits":["1x","light"]}]},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/Getting-Started":{"role":"article","title":"Getting started","abstract":[{"type":"text","text":"This article describes how to get started with EmojiKit."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Getting-Started","kind":"article","type":"topic","url":"\/documentation\/emojikit\/getting-started"},"emoji-grid-vertical.png":{"alt":"Emoji Grid","type":"image","identifier":"emoji-grid-vertical.png","variants":[{"url":"\/images\/emoji-grid-vertical.png","traits":["1x","light"]}]},"emoji-picker-callout.png":{"alt":"Emoji Picker Callouts","type":"image","identifier":"emoji-picker-callout.png","variants":[{"url":"\/images\/emoji-picker-callout.png","traits":["1x","light"]}]},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/Emoji/Picker":{"role":"symbol","title":"Emoji.Picker","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Picker"}],"abstract":[{"type":"text","text":"This view lists emojis in a vertical or horizontal grid."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Emoji\/Picker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Picker"}],"url":"\/documentation\/emojikit\/emoji\/picker"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit/Emoji/Grid":{"role":"symbol","title":"Emoji.Grid","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Grid"}],"abstract":[{"type":"text","text":"This view lists emojis in a vertical or horizontal grid."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Emoji\/Grid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Grid"}],"url":"\/documentation\/emojikit\/emoji\/grid"},"doc://com.kankoda.EmojiKit/documentation/EmojiKit":{"role":"collection","title":"EmojiKit","abstract":[{"type":"text","text":"EmojiKit is helps you manage emojis in your Swift-based software."}],"identifier":"doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit","kind":"symbol","type":"topic","url":"\/documentation\/emojikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Getting-Started","doc:\/\/com.kankoda.EmojiKit\/documentation\/EmojiKit\/Features"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}